server:
    port: 8081

spring:
    datasource:
      url: jdbc:postgresql://localhost:5433/produto
      username: demo
      password: demo

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true

estoque:
    base-url: http://localhost:8082

security:
  jwt:
    secret: "u8$9JvQZxT2pL!mC5$4%*7&!#k7qY4sF%tP6^Nd3B&XcR1gV*LwUzEoM!hS9Kf2y"
    expiration: 3600000
